config/routes.rb
Stockroom::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :categories do 
    resources :items
  end
  resources :items do
    member do
      get :reload
    end
  end
  resources :targets
  resources :transactions do
      member do
        post :decline
      end
    
    collection do
      get 'report_page'
      get 'report_by_target'
    end
  end
  root "items#index"
  get "home", to: "pages#home", as: "home"
  get "danger", to: "items#danger", as: "danger"
  get "wrong_balance", to: "items#wrong_balance", as: "wrong_balance"
  get "inside", to: "pages#inside", as: "inside"
  get "report", to: "pages#report", as: "report"
  get "/contact", to: "pages#contact", as: "contact"
  post "/emailconfirmation", to: "pages#email", as: "email_confirmation"

  get "posts", to: "pages#posts", as: "posts"
  get "posts/:id", to: "pages#show_post", as: "post"
  devise_for :users

  namespace :admin do
    root "base#index"
    resources :users
    get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
    get "posts/dashboard", to: "posts#dashboard", as: "posts_dashboard"
    resources :posts
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  # Use friendly_id
  extend FriendlyId
  friendly_id :title, use: :slugged

  # Markdown
  before_save { MarkdownWriter.update_html(self) }

  # Validations
  validates :title, presence: true, length: { maximum: 100 }, uniqueness: true
  validates :content_md, presence: true

  # Pagination
  paginates_per 30

  # Relations
  belongs_to :user

  # Scopes
  scope :published, lambda {
    where(draft: false)
    .order("updated_at DESC")
  }

  scope :drafted, lambda {
    where(draft: true)
    .order("updated_at DESC")
  }

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController

  before_action :set_post, only: [
    :edit,
    :update,
    :destroy
  ]


  def dashboard
    @published_post_count = Post.published.count
    @draft_post_count = Post.drafted.count
  end

  def index
    @posts = Post.published.page(params[:page]).per(50)
  end

  def drafts
    @posts = Post.drafted.page(params[:page]).per(50)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to admin_posts_dashboard_path, notice: "New post published."
    else
      flash[:alert] = "Post not published."
      render :new
    end
  end

  def edit
  end

  def update
    @post.slug = nil
    if @post.update(post_params)
      redirect_to admin_posts_dashboard_path, notice: "Post successfully edited."
    else
      flash[:alert] = "The post was not edited."
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to admin_posts_path, notice: "The post has been deleted."
  end


  private

  def set_post
    @post = Post.friendly.find(params[:id])
  end

  def post_params
    params.require(:post).permit(
    :title,
    :content_md,
    :draft,
    :updated_at
    )
  end


end

app/views/admin/posts/_form.html.erb
<% if @post.errors.any? %>
<ul>
  <% @post.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for [:admin, @post], role: "form" do |f| %>

<div class="form-group">
  <%= f.label :title %>
  <div class="row">
    <div class="col-xs-12">
      <%= f.text_field :title, :autofocus => true, class: "form-control monospaced-control", placeholder: "Title (also used for URL slug)..." %>
    </div>
  </div>
</div>

<div class="form-group">
  <%= f.label :content_md, "Content" %>
  <div class="row">
    <div class="col-xs-12">
      <%= f.text_area :content_md, rows: 15, class: "form-control monospaced-control", placeholder: "Post content (Markdown format)..." %>
    </div>
  </div>
</div>

<div class="form-group">
  <div class="row">
    <div class="col-xs-12">
      <%= f.check_box :draft %> <%= f.label :draft, "draft" %>
    </div>
  </div>
</div>

<div class="form-group">
  <%= f.label :updated_at, "Published date" %>
  <div class="row">
    <div class="col-xs-12">
      <%= f.datetime_select :updated_at, class: "form-control" %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-12 padded">
    <button class='btn btn-primary'>
      <i class='fa fa-plus-square'></i> Publish
    </button> - <%= link_to "Cancel", admin_posts_dashboard_path %>
  </div>
</div>

<% end %>

app/views/admin/posts/dashboard.html.erb
<% title("Posts Dashboard") %>
<h3 class="page-title">Posts <small>Dashboard</small></h3>
<p><%= link_to "Back to Admin", admin_root_path %></p>
<hr/>
<div class="row">
  <div class="col-sm-4">Published: <%= link_to "#{pluralize(@published_post_count, 'post')}", admin_posts_path %></div>
  <div class="col-sm-4">Drafts: <%= link_to "#{pluralize(@draft_post_count, 'draft')}", admin_posts_drafts_path %></div>
  <div class="col-sm-4"><%= link_to "New post", new_admin_post_path %></div>
</div>

app/views/admin/posts/drafts.html.erb
<% title("Post Drafts") %>
<h3 class="page-title">Posts <small>Drafts</small></h3>
<p><%= link_to "Back to dashboard", admin_posts_dashboard_path %></p>
<hr/>

<p class="pagination-summary"><%= page_entries_info @posts %></p>
<%= paginate @posts %>

<hr/>

<ul class="fa-ul">
  <% @posts.each do |post| %>
  <li class="margin-md-down">
    <i class="fa fa-arrow-circle-o-right small"></i>&nbsp;&nbsp;
    <%= link_to post.title, edit_admin_post_path(post.slug) %> <br/>
    <small class="x-small-text">about <%= time_ago_in_words(post.updated_at) %> ago</small>
  </li>
  <% end %>
</ul>

<hr/>

<%= paginate @posts %>

app/views/admin/posts/edit.html.erb
<% title("Edit #{@post.title}") %>
<h3 class="page-title">Edit post <small><%= @post.title %></small></h3>
<p>
  <%= link_to "Back to dashboard", admin_posts_dashboard_path %>
</p>
<hr/>

<%= render 'form' %>
<hr/>
<%= link_to "<i class='fa fa-minus-square'></i> Delete post".html_safe, admin_post_path(@post), method: :delete, data:{confirm: "Are you sure?"}, class: "btn btn-small btn-danger" %>

app/views/admin/posts/index.html.erb
<% title("Published posts") %>
<h3 class="page-title">Posts <small>Published</small></h3>
<p><%= link_to "Back to dashboard", admin_posts_dashboard_path %></p>
<hr/>

<p class="pagination-summary"><%= page_entries_info @posts %></p>
<%= paginate @posts %>

<hr/>

<ul class="fa-ul">
  <% @posts.each do |post| %>
  <li class="margin-md-down">
    <i class="fa fa-arrow-circle-o-right small"></i>&nbsp;&nbsp;
    <%= link_to post.title, edit_admin_post_path(post.slug) %> <br/>
    <small class="x-small-text">about <%= time_ago_in_words(post.updated_at) %> ago</small>
  </li>
  <% end %>
</ul>

<hr/>

<%= paginate @posts %>

app/views/admin/posts/new.html.erb
<% title("New post") %>
<h3 class="page-title">Add a new post</h3>
<p><%= link_to "Back to dashboard", admin_posts_dashboard_path %></p>
<hr/>

<%= render 'form' %>