config/routes.rb
Stockroom::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :categories do 
    resources :items
  end
  resources :items do
    member do
      get :reload
    end
  end
  resources :targets
  resources :transactions do
      member do
        post :decline
      end
    
    collection do
      get 'report_page'
      get 'report_by_target'
    end
  end
  root "items#index"
  get "home", to: "pages#home", as: "home"
  get "danger", to: "items#danger", as: "danger"
  get "wrong_balance", to: "items#wrong_balance", as: "wrong_balance"
  get "inside", to: "pages#inside", as: "inside"
  get "report", to: "pages#report", as: "report"
  get "/contact", to: "pages#contact", as: "contact"
  post "/emailconfirmation", to: "pages#email", as: "email_confirmation"

  get "posts", to: "pages#posts", as: "posts"
  get "posts/:id", to: "pages#show_post", as: "post"
  devise_for :users

  namespace :admin do
    root "base#index"
    resources :users
    get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
    get "posts/dashboard", to: "posts#dashboard", as: "posts_dashboard"
    resources :posts
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :items,  dependent: :destroy
  belongs_to :user
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    
    @q = Category.ransack(params[:q])
   # if params[:category_id] 
   #   @q.category_id_eq = params[:category_id]
   # end
    @categories = @q.result
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    #@items = @category.items
   
    @q = @category.items.ransack(params[:q])
    if params[:category_id] 
      @q.category_id_eq = params[:category_id]
    end
    @items = @q.result
  
    @items = @items.page(params[:page])
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description, :item_ids => [])
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for @category, :html => { :class => 'form-horizontal col-md-6' } do |f| %>
  <%= f.input :name,  :label => "Название"  %>
  <%= f.error_span(:name) %>
  <%#= f.association :user,  collection: User.order(:email), prompt: "Выбирите менеджера", label_method: :email %>
  <%#= f.error_span(:user) %>
  <%= f.input :description, :label => "Описание"%>
  <%= f.error_span(:description) %>
  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                categories_path, :class => 'btn btn-default' %>
<% end %>

app/views/categories/edit.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/categories/index.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h3> Категории </h3>
</div>

<% content_for :sidebar do %>
<div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">Поиск Категорий</div>
        <div class="panel-body">
         <%= ransack_simple_form_for @q , :html => { :class => 'form-vertical ' } do |f| %>
              <%= f.input  :name_cont  , :label => "Наименование" ,:include_blank => true %>
              <%= f.button :submit, "Поиск", :class => 'btn-primary btn-block' %>
          <% end %>
        </div>
      </div>
    </div>

<% end %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_category_path,
            :class => 'btn btn-primary' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Назв. </th>
      <th>Описание </th>
      <th>Количество ед. </th>
      <th>Баланс</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.name, category_path(category) %></td>
        <td><%= category.description %></td>
        <td><%= category.items_count %></td>
        <td><%= category.total_cost %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      category_path(category), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_category_path(category), :class => 'btn btn-default btn-xs' %>
                      
          
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      category_path(category),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => "btn btn-xs btn-danger  #{ 'disabled' if category.total_cost > 0}" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_category_path,
            :class => 'btn btn-primary' %>

app/views/categories/new.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/categories/show.html.erb
<%- model_class = Category -%>
 
 <blockquote>
  <strong class="text-success"><%= @category.name rescue ''%></strong>
  <%= link_to "Добавить наименованние", new_category_item_path(:category_id => @category.id),
            :class => 'btn btn-xs btn-default pull-centr ' %>
</blockquote>

<% content_for :sidebar do %>
   <div class="">
    <%= render "layouts/categories" %>
  </div>

  <%#= render "layouts/items_form_search" %>
  
 
<% end %>
 <%= ransack_simple_form_for @q , url: category_path(@category), :html => { :method => :get, :class => 'form-inline ' } do |f| %>
    <%= f.input  :name_cont  ,placeholder:'Поиск...' , :label => false ,:include_blank => true %>
    <%= f.button :submit, "Поиск", :class => 'btn-primary ' %>
  <% end %>


<%= paginate @items, window: 2 , :theme => 'twitter-bootstrap-3' %>
<div class="col-md-12">
  <table class="table table-striped  table-hover">
    <thead>
      <tr>
        <th>Наименование</th>
        <th></th>
        <th>Цена</th>
        <th>К-во</th>
        <th></th>
        <th>Total</th>
        <th>Действия</th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
        <tr>
          <!--td><strong><%= link_to truncate("  #{item.category.name}", length: 27, separator: ' ') , category_item_path(item.category, item) %></td></strong--!>
          <td><strong><%= link_to truncate("  #{item.name}", length: 70, separator: ' ') , category_item_path(item.category, item) %></td></strong>
          
          <td><strong class="text-muted"><%= item.last_income %></strong>   </td>
          <td><%= item.price.format %> </td>
          <td>
            <% if item.amount < item.red_line %>
              <span class="label label-danger"> <%= item.amount %></span> <%= item.unit_type %>
            <% else %>
              <%= item.amount %> <%= item.unit_type %>
            <% end %>
          </td>
          
          <td>  </td>
          <td class="info" ><strong><%= item.total.format %> </strong> </td>
          <td>
          <%= link_to  'Получить',
            new_transaction_path(:item_id=> item, :action_type => "In"), :class => 'btn btn-default btn-xs' %>
            
            <% if item.amount > 0 %>
            <%= link_to  'Выдать',
              new_transaction_path(:item_id=> item, :action_type => "Out"), :class => 'btn btn-default btn-xs' %>
            <% else %>
              <%= link_to  'Выдать',
                new_transaction_path(:item_id=> item, :action_type => "Out"), :class => 'btn btn-default btn-xs disabled' %>
            <% end %> 
              <%#= link_to t('show', :default => t("helpers.links.show")),
                        item_path(item), :class => 'btn btn-default btn-xs' %>
          <%- if current_user.admin? %>
            <%= link_to t('edit', :default => t("helpers.links.edit")),
                        edit_item_path(item), :class => 'btn btn-default btn-xs' %>
                      
              <%= link_to 'Обнулить',
                        reload_item_path(item), :class => 'btn btn-primary btn-xs' %>
             <% end %>           
                      
            <% if item.amount == 0 %>            
            <%= link_to t('destroy', :default => t("helpers.links.destroy")),
                        category_item_path(item.category, item),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
                    <% end %> 
                     
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @items, window: 2 , :theme => 'twitter-bootstrap-3' %>
  <%= link_to "Добавить наименованние",
  new_category_item_path(:category_id => @category.id),
            :class => 'btn btn-default' %>
</div>

<%
=begin
%>              
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_category_path(@category), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              category_path(@category),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

<%
=end
%>              