config/routes.rb
Stockroom::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :categories do 
    resources :items
  end
  resources :items do
    member do
      get :reload
    end
  end
  resources :targets
  resources :transactions do
      member do
        post :decline
      end
    
    collection do
      get 'report_page'
      get 'report_by_target'
    end
  end
  root "items#index"
  get "home", to: "pages#home", as: "home"
  get "danger", to: "items#danger", as: "danger"
  get "wrong_balance", to: "items#wrong_balance", as: "wrong_balance"
  get "inside", to: "pages#inside", as: "inside"
  get "report", to: "pages#report", as: "report"
  get "/contact", to: "pages#contact", as: "contact"
  post "/emailconfirmation", to: "pages#email", as: "email_confirmation"

  get "posts", to: "pages#posts", as: "posts"
  get "posts/:id", to: "pages#show_post", as: "post"
  devise_for :users

  namespace :admin do
    root "base#index"
    resources :users
    get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
    get "posts/dashboard", to: "posts#dashboard", as: "posts_dashboard"
    resources :posts
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy, :decline]

  # GET /transactions
  # GET /transactions.json
  def index
   # @q = Transaction.ransack(params[:q])
   # @transactions = @q.result.page(params[:page])
   # @total_count
  
    params[:q] ||= {}
    if params[:q][:created_at_lteq].present?
      params[:q][:created_at_lteq] = params[:q][:created_at_lteq].to_date.end_of_day
    end
    if params[:q][:created_at_gteq].present?
      params[:q][:created_at_gteq] = params[:q][:created_at_gteq].to_date.beginning_of_day
    end  
    @q = Transaction.ransack(params[:q])
     
      if params[:item_id] 
        @q.item_id_eq = params[:item_id]
      end
      if params[:target_id] 
        @q.target_id_eq = params[:target_id]
      end
      
      @transactions  = @q.result
     
    #   binding.pry
      count_total_plus_and_minus(@transactions)
      count_target(@transactions)
      calculate_stats(@transactions)
      @total_income = @transactions.where(:action_type => "In").sum(:cost)
      @total_out    = @transactions.where(:action_type => "Out").sum(:cost)
      @transactions = @transactions.page(params[:page])
    
  
  end
  
  def report_page
    @q = Transaction.ransack(params[:q])
    @transactions  = @q.result
    count_total_plus_and_minus(@transactions)
    count_target(@transactions)
    calculate_stats(@transactions)
    @transactions = @transactions.page(params[:page])
  end
  

  def report_by_target
    params[:q] ||= {}
    if params[:q][:created_at_lteq].present?
      params[:q][:created_at_lteq] = params[:q][:created_at_lteq].to_date.end_of_day
    end
    if params[:q][:created_at_gteq].present?
      params[:q][:created_at_gteq] = params[:q][:created_at_gteq].to_date.beginning_of_day
    end
    @q = Transaction.where(:action_type => "Out").ransack(params[:q])
    @transactions  = @q.result
   # @stats        =  @transactions.group(:item_id).count rescue nil
    @stats= {}
    @transactions.find_each do |t|
      if @stats[t.item_id]
        @stats[t.item_id]= @stats[t.item_id] + t.amount
      else
        @stats[t.item_id]= t.amount
      end
    end
    
    @transactions = @transactions.page(params[:page])

  end
  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new(:item_id => params[:item_id], :action_type => params[:action_type])
    
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)
    respond_to do |format|
      if @transaction.save
        @item = @transaction.item
        case @transaction.action_type
        when "In"
          @item.amount += @transaction.amount
        when "Out"
          @item.amount = @item.amount - @transaction.amount
        end 
          @item.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end
 
  
  def decline
      @item = @transaction.item
        case @transaction.action_type
        when "In"
          @item.amount = @item.amount - @transaction.amount
          @transaction.action_type="In-Canceled"
        when "Out"
          @item.amount += @transaction.amount
          @transaction.action_type="Out-Canceled"
        end 
      @transaction.destroy
      @item.save
      respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Транзакция успешно отменена' }
      format.json { head :no_content }
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    
    
  def count_target(transactions)
    @users    ={}
    targets  ={}  
    User.find_each do |user|
      Target.find_each do |target|
          total = 0 
          total = user.transactions.where(:target_id => target.id, :action_type => "Out").sum(:amount)
          targets[target.id] = total
      end  
      max_target= targets.max_by{ |k,v| v }[1]
      targets["max_target" => max_target]
      @users["#{user.email}" => targets ]  
      
    end  
    @users
  end

  
  def calculate_stats(transactions)
    @report_by_target = {}
    @report_by_category = {}
    #Category.find_each do |category|
    #  transactions.where(:target_id => target.id, :action_type => "Out")
    #end
   #category_ids =[]
   #transactions.find_each do |transaction|
   # #@report_by_category[] 
   #  transaction.item.category_id
   #  category_ids << 
   #end    
        
    Target.find_each do |target|   
      @report_by_target[target.name] = transactions.where(:target_id => target.id).sum(:cost)
    end
  end  
  
  def count_total_plus_and_minus(transactions)
      @total_plus = 0
      @total_by_target = 0
      @total_minus = 0
      @total_transactions = 0 
      
      transactions.find_each do |t|
         @total_transactions += 1 
         case t.action_type
          when "In"
           @total_plus += t.cost    
          when "Out"
           @total_minus += t.cost    
           #:@total_by_target += t.amount.to_i if t.
          end
      end  
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end
    
    def render_report(transactions)
        send_data Transaction.report(transactions).generate, filename: 'report.pdf',
                               type: 'application/pdf',
                               disposition: 'attachment'
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:item_id, :action_type, :amount, :target_id, :notes, :user_id, :category_id)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= simple_form_for @transaction, :html => { :class => 'form-horizontal col-md-4' } do |f| %>
  <%= f.association :item, :label => "Позиция" , :readonly => true, required: true %>
  <%= f.error_span( :item_id ) %>
  <%= f.association :user, as: :hidden, input_html: { value: current_user.id } %>
  <%= f.error_span( :user_id ) %>
  <%= f.input :action_type, collection: [ ["Приход на склад","In"], ["Выдача на станцию","Out"]], :readonly => true , :label => "Тип операции "%>
  <%= f.error_span(:action_type) %>
  <% if @transaction.action_type == "Out"%> 
    <%= f.input :amount , :label => "Количетсво (макс. #{ @transaction.item.amount })" , required: true , input_html: { min: '1', max: @transaction.item.amount }%>
  <% else %>
    <%= f.input :amount , :label => "Количетсво " , required: true , input_html: { min: '1' }%>
  <% end %>  
  <%= f.error_span(:amount) %>
  <% if @transaction.action_type == "Out"%> 
    <%= f.association :target , :label => "Пункт назначения (Станция №1, ... )" , required: true %>
  <% end %>
  <%= f.error_span(:target_id) %>
  <%= f.input :notes , :label => "Заметки"%>
  <%= f.error_span(:notes) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                transactions_path, :class => 'btn btn-default' %>
<% end %>

app/views/transactions/_transaction_row.html.erb
        <td><%= link_to transaction.category_name, category_path(transaction.item.category) rescue ''%></td>
        <td><%= link_to transaction.item.name, category_item_path(transaction.item.category, transaction.item) %></td>
        <%- case transaction.action_type %>
        <% when "In" %>
          <td><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span></td>
          <td><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></td>
        <% when "Out" %>
          <td><span class="glyphicon glyphicon-export" aria-hidden="true"></span></td>
          <td><%= transaction.target.name rescue 'unknown'  %></td>
        <% end %>
        <td class="hidden-print"><%=  transaction.user.email rescue '-'  %> </td>
        
        <td><%= transaction.created_at.strftime("%d/%m %H:%M") rescue '-' %></td>
        
        <td><%= transaction.amount %> <%= transaction.item.unit_type%> x <%= transaction.item.price%> </td>
        
        <% if transaction.action_type == "In" %>
          <td class="info" > <strong>+ <%= transaction.cost  %> грн.</strong></td>
        <% else %>
          <td class="danger" > <strong>- <%= transaction.cost  %> грн.</strong></td>
          <% end %>  
        <td class="hidden-print">
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      transaction_path(transaction), :class => 'btn btn-default btn-xs' %>
          <%#= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_transaction_path(transaction), :class => 'btn btn-default btn-xs' %>
                    <%= link_to "Отмена",
                      decline_transaction_path(transaction),
                      :method => :post,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>

                    
                    <%- if current_user.admin? %> 
                    <%#= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      transaction_path(transaction),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
      
          <% end %>
        </td>

app/views/transactions/edit.html.erb
<%- model_class = Transaction -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/transactions/index.html.erb
<!-- Small modal -->
<%- model_class = Transaction -%>
<div class="page-header hidden-print">
  <h3><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h3>
</div>

<div class="col-xs-12">
  
<dl class="dl-horizontal ">
  <dt><strong>Приход на склад:</strong></dt>
  <dd><%= @total_income %> .грн</dd>
  <dt><strong>Выдача:</strong></dt>
  <dd><%= @total_out %> .грн</dd>
</dl>  
<%= paginate @transactions,  :theme => 'twitter-bootstrap-3' %>
<table class="table table-responsive table-striped table-hover ">
  <thead>
    <tr>
      <th><%= sort_link(@q, :category) %> </th>
      <th>Позиция</th>
      <th style="max-width:20%;"><%= sort_link(@q, :action_type, "-+") %></th>
      <th>Станция</th>
      <th class="hidden-print">Опер.</th>
      <th><%= sort_link(@q, :created_at, "Дата") %></th>
      <th>N</th>
      <th></th>
      <th class="hidden-print"></th>
    </tr>
  </thead>
  <tbody>
    <% @transactions.each do |transaction| %>
      <% begin %>
      <tr>  
        <%= render :partial => 'transaction_row', :locals => {:transaction => transaction} %>
      </tr>  
    <% end %>
    <% end %>
  </tbody>
</table>

<%= paginate @transactions,  :theme => 'twitter-bootstrap-3' %>
<%#= link_to t('.new', :default => t("helpers.links.new")),
            new_transaction_path,
            :class => 'btn btn-primary' %>
  </div>
   <% content_for :sidebar do %>
 
  <div class="col-lg-12 hidden-print">
  <div class="panel panel-default">
    <div class="panel-heading">Поиск по транзакциям</div>
    <div class="panel-body">
        <%= ransack_simple_form_for @q , :html => { :class => 'form-vertical ' } do |f| %>
           <%= f.input  :target_id_eq ,:collection => Target.all, :label_method => :name, :value_method => :id, :label => "Станция" ,:include_blank => true %>
           <%= f.input  :item_category_id_eq ,:collection => Category.all, :label_method => :name, :value_method => :id, :label => "Категория" ,:include_blank => true %>
           <%#= f.input  :item_id_eq ,:collection => Item.all, :label_method => :name, :value_method => :id, :label => "Продукт" ,:include_blank => true %>
           <%= f.input  :item_name_cont , :label => "Продукт" ,:include_blank => true %>
           
           <%= f.input  :user_id_eq ,:collection => User.all, :label_method => :email, :value_method => :id, :label => "Оператор" ,:include_blank => true %>
           <%#= f.input  :item_name_eq ,:collection => Account::CARD_TYPES,  :label => "Тип карты" ,:include_blank => true %>
           <%= f.input  :action_type_eq ,   :collection => ['In','Out'],  :label => "Тип Транзакции" ,:include_blank => true %>
           <h5><strong class="text-info">Транзакции созданы в период:</strong></h5> 
           <%= f.input  :created_at_gteq, as: :date, default: Date.today.at_beginning_of_month, :label => "От:" ,:include_blank => false, class: 'form-control  '%>
            <%= f.input :created_at_end_of_day_lteq, as: :date,  default: Date.today, :label => "До:" ,:include_blank => false, class: 'form-contol'  %>
            <br/>
            <div class="row">
              <div class="col-md-6">
                <%= f.input :cost_gteq , label: 'Сумма от'%>
              </div>
              <div class="col-md-6">
                <%= f.input :cost_lteq , label: '- до'%>
              </div>
            </div>
        <%= f.button :submit, "Поиск", :class => 'btn-primary btn-block' %>
      <% end %>
   
    
    </div>
  </div>
  

<%- if current_user.admin? %> 
    <div class="panel panel-primary">
      <div class="panel-heading"> Аналитика  <%= Transaction.check_balance %> </div>
      <div class="panel-body">
        <dl class="dl-horizontal">
          <dt><strong>Приход:</strong></dt>
          <dd><%= @total_plus %> .грн</dd>
          <dt><strong>Расход:</strong></dt>
          <dd><%= @total_minus %> .грн</dd>
          <dt><strong>Кол-во операций.:</strong></dt>
          <dd><%= @total_transactions %></dd>
        </dl>
        <strong>По станциям</strong>
        <dl class="dl-horizontal">
          <%- @report_by_target.each do |key,value| %>
            <% if value > 0 %>
              <dt><strong><%= key %>:</strong></dt>
              <dd><%= value %> .грн</dd>
            <% end %>  
          <% end %>
        </dl>
      </div>
    </div>
    
      
  <% end %>

  </div>
<% end %>

app/views/transactions/new.html.erb
<%- model_class = Transaction -%>
<div class="page-header">
  <h3><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h3>
</div>
<%= render :partial => 'form' %>

app/views/transactions/report_by_target.html.erb
<% content_for :sidebar do %>
 
  <div class="col-sm-12 hidden-print">
  <div class="panel panel-default">
    <div class="panel-heading">Параметры Отчета</div>
    <div class="panel-body">
        <%= ransack_simple_form_for @q, url: report_by_target_transactions_path , :html => { :class => 'form-vertical ' } do |f| %>
           <h5><strong class="text-info">Отчетность за период:</strong></h5> 
           <%= f.input  :target_id_eq ,:collection => Target.all, :label_method => :name, :value_method => :id, :label => "Станция" ,:include_blank => false %>
           <%= f.input  :created_at_gteq, as: :date, default: Date.today.at_beginning_of_month, :label => "От:" ,:include_blank => false, class: 'form-control  '%>
           <%= f.input :created_at_end_of_day_lteq, as: :date, default: Date.today, :label => "До:" ,:include_blank => false, class: 'form-contol'  %>
            <br/>
        <%= f.button :submit, "Сгенерировать", :class => 'btn-primary btn-block' %>
  <% end %>
   
    
    </div>
  </div>
  </div>
<% end %>

<% if params[:q].size > 0 %>
<div class="col-xs-12">
  <div class="page-header text-center">
    <h3>Отчет расходов по станции: 
      <br />
      <strong>"<%= Target.find(params[:q]["target_id_eq"]).name rescue '' %>" </strong>
      <br />

      <%#= params[:q]["created_at_gteq"].to_date.strftime("%d/%m/%Y")  rescue '-' %> <%#= params[:q]["created_at_lteq"].to_date.strftime("%d/%m/%Y")  rescue '-' %>
    </h3>
  </div>

  <table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Позиция</th>
      <th>К-во</th>
    </tr>
  </thead>
  <tbody>
    <% @stats.each do |key,value| %>
      <% begin %>
      <%  item = Item.with_deleted.find(key) rescue nil %>
      <% if item %>
        <tr>
          <td><%= item.name %> </td>
          <td> <%= value %> <%= item.unit_type %></td>
        </tr>
    <% end %>
    <% end %>
    <% end %>
  </tbody>
</table>

</div>
<% end %>

app/views/transactions/report_page.html.erb
<% content_for :sidebar do %>
 
  <div class="col-sm-12">
  <div class="panel panel-default">
    <div class="panel-heading">Параметры Отчета</div>
    <div class="panel-body">
        <%= ransack_simple_form_for @q, url: report_page_transactions_path , :html => { :class => 'form-vertical ' } do |f| %>
           <h5><strong class="text-info">Отчетность за период:</strong></h5> 
           <%= f.input  :created_at_gteq, as: :date,  :label => "От:" ,:include_blank => true, class: 'form-control  '%>
            <%= f.input :created_at_lteq, as: :date,   :label => "До:" ,:include_blank => true, class: 'form-contol'  %>
            <br/>
        <%= f.button :submit, "Сгенерировать", :class => 'btn-primary btn-block' %>
      <% end %>
   
    
    </div>
  </div>
  </div>
 
 
  <div class="col-sm-12">
  <div class="panel panel-default">
    <div class="panel-heading"> Общая статистика</div>
    <div class="panel-body">
       <dl class="dl-horizontal">
              <dt><strong> Поступления:</strong></dt>
              <dd><%= Transaction.total_in %> .грн</dd>
              <dt><strong>Баланс склада:</strong></dt>
              <dd><%= Item.sum(:total) %> .грн</dd>
              <dt><strong>Расход:</strong></dt>
              <dd><%= Transaction.total_out %> .грн</dd>
              <hr>
              <%- if Transaction.check_balance > 0 %>
                <dt><strong>Избыток:</strong></dt>
              <% else %>
                <dt><strong>Недостача:</strong></dt>
              <% end %>  
              <dd><%= Transaction.check_balance %> .грн</dd>
            </dl>

    
    </div>
  </div>
  </div>
 
<% end %>


<div class="col-sm-12">
  <div class="panel panel-default">
    <div class="panel-heading">Отчет</div>
    <div class="panel-body">
      
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading"> Склад </div>
          <div class="panel-body">
            <dl class="dl-horizontal">
              <dt><strong>Поступления:</strong></dt>
              <dd><%= @total_plus %> .грн</dd>
              <dt><strong>Расход:</strong></dt>
              <dd><%= @total_minus %> .грн</dd>
              <dt><strong>Кол-во операций.:</strong></dt>
              <dd><%= @total_transactions %></dd>
            </dl>

          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading">По станциям</div>
          <div class="panel-body">
            <dl class="dl-horizontal">
              <%- @report_by_target.each do |key,value| %>
              <dt><strong><%= key %>:</strong></dt>
              <dd><%= value %> .грн</dd>
              <% end %>
            </dl>

          </div>
        </div>
      </div>
      
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading"> По категориям </div>
          <div class="panel-body">
            <dl class="dl-horizontal">
              <dt><strong>Поступления:</strong></dt>
              <dd><%= @total_plus %> .грн</dd>
              <dt><strong>Расход:</strong></dt>
              <dd><%= @total_minus %> .грн</dd>
              <dt><strong>Кол-во операций.:</strong></dt>
              <dd><%= @total_transactions %></dd>
            </dl>

          </div>
        </div>
      </div>

    
    </div>
  </div>
  </div>

app/views/transactions/show.html.erb
<%- model_class = Transaction -%>
<div class="page-header">
  <h3><%=t '.title', :default => model_class.model_name.human.titleize %></h3>
</div>

<dl class="dl-horizontal">
  <dt><strong>#:</strong></dt>
  <dd><%= @transaction.item_id %></dd>
  <dt><strong>Количество:</strong></dt>
  <dd><%= @transaction.amount %></dd>
  <dt><strong>Тип транзакции:</strong></dt>
  <% if @transaction.action_type == "Out"%> 
    <dd>Выдача на станцию</dd>
    <dt><strong>Пункт назначения:</strong></dt>
    <dd><%= @transaction.target_id %></dd>
  <% else %>
    <dd> Приход на склад</dd>
  <% end %>  
  <dt><strong>Заметки:</strong></dt>
  <dd><%= @transaction.notes %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              transactions_path, :class => 'btn btn-default'  %>
<%#= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_transaction_path(@transaction), :class => 'btn btn-default' %>
<%#= link_to t('.destroy', :default => t("helpers.links.destroy")),
              transaction_path(@transaction),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>