config/routes.rb
Stockroom::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :categories do 
    resources :items
  end
  resources :items do
    member do
      get :reload
    end
  end
  resources :targets
  resources :transactions do
      member do
        post :decline
      end
    
    collection do
      get 'report_page'
      get 'report_by_target'
    end
  end
  root "items#index"
  get "home", to: "pages#home", as: "home"
  get "danger", to: "items#danger", as: "danger"
  get "wrong_balance", to: "items#wrong_balance", as: "wrong_balance"
  get "inside", to: "pages#inside", as: "inside"
  get "report", to: "pages#report", as: "report"
  get "/contact", to: "pages#contact", as: "contact"
  post "/emailconfirmation", to: "pages#email", as: "email_confirmation"

  get "posts", to: "pages#posts", as: "posts"
  get "posts/:id", to: "pages#show_post", as: "post"
  devise_for :users

  namespace :admin do
    root "base#index"
    resources :users
    get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
    get "posts/dashboard", to: "posts#dashboard", as: "posts_dashboard"
    resources :posts
  end

end

app/views/layouts/_categories.html.erb
<div class="">
  <div class="list-group">
    <% Category.find_each do |category| %>
      <a href="<%= category_path(category) %>" class="list-group-item <%= 'active' if @category == category %>"><%= category.name %>  <span class="badge"> <%=category.items_count %> </span> </a>
    <% end %>
   </div>
  <%= link_to 'Редактировать', categories_path, :class=>"btn btn-block" %>
</div>

app/views/layouts/_footer.html.erb
<div id="footer" class=" hidden-print">
  <div class="container">

    <div class="row footer-first-row">

      <div class="col-xs-12 text-center">
        <p><small>
          &copy; <%= Time.now.year %> - Paul M.!
          <br/>
        </small></p>
      </div>

    </div>

  </div>
</div>

app/views/layouts/_items_form_search.html.erb
<div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">Поиск инвентаря</div>
        <div class="panel-body">
         <%= ransack_simple_form_for @q , :html => { :class => 'form-vertical ' } do |f| %>
              <%= f.input  :category_id_eq ,:collection => Category.all, :label_method => :name, :value_method => :id, :label => "Категория" ,:include_blank => true %>
              <%= f.input  :name_cont  , :label => "Наименование" ,:include_blank => true %>
              <%= f.input  :description_cont  , :label => "Описание" ,:include_blank => true %>
              
              <%= f.input  :sku_cont  , :label => "SKU" ,:include_blank => true %>
              <%= f.button :submit, "Поиск", :class => 'btn-primary btn-block' %>
          <% end %>
        </div>
      </div>
    </div>
   

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
<% if msg.is_a?(String) %>
<div class="alert alert-<%= name == "notice" ? "success" : "danger" %>">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
</div>
<% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header active">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%- if Category.count > 0 %>
        <%= active_link_to 'Склад', category_path(Category.first),  :active => [['categories'], ['show']], class: 'brand active navbar-brand' %>
      <% else %>
        <%= link_to 'Склад', categories_path, class: 'navbar-brand'%>
      <% end %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<% if !user_signed_in? %>
<li><%= active_link_to "Вход", new_user_session_path %></li>
<li><%= active_link_to "Регистрация", new_user_registration_path %></li>
<% else %>
<li><%#= link_to "Наименования", items_path %></li>
<%= active_link_to "Критический",   danger_path, :wrap_tag => :li %>
<%= active_link_to "Баланс",   wrong_balance_path, :wrap_tag => :li %>
<%= active_link_to "Транзакции",   transactions_path, :wrap_tag => :li, :active => [['transactions'], ['index']]%>
<%= active_link_to "Поиск",   items_path, :wrap_tag => :li, :active => [['items'], ['index']]%>
<%= active_link_to "Пункты назначения", targets_path , :wrap_tag => :li%>
<%= active_link_to "Категории", categories_path, :wrap_tag => :li , :active => [['categories'], ['index','edit']]%>
<%= active_link_to "Отчет",  report_by_target_transactions_path , :wrap_tag => :li, :active => [['transactions'], ['report_by_target']]%>
<%= active_link_to "Редактировать профайл", edit_user_registration_path , :wrap_tag => :li%>

<% if current_user.admin? %>
  <%= active_link_to "Admin", admin_root_path, :wrap_tag => :li %>
<% end %>

<%= active_link_to "Sign out", destroy_user_session_path, data:{method: :delete}, :wrap_tag => :li %>
<% end %>

app/views/layouts/_targets_form_search.html.erb
<div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">Поиск Станций</div>
        <div class="panel-body">
         <%= ransack_simple_form_for @q , :html => { :class => 'form-vertical ' } do |f| %>
              <%= f.input  :name_cont  , :label => "Наименование" ,:include_blank => true %>
              <%= f.button :submit, "Поиск", :class => 'btn-primary btn-block' %>
          <% end %>
        </div>
      </div>
    </div>

app/views/layouts/_targets_list.html.erb
Targets <%= @users.to_s %>
<%- @users.each do |user| %>
  <%= user[target.to_s] %>  
<div class="panel panel-default">
  <div class="panel-heading">Пункты: <%= user.email %>  </div>
    <div class="panel-body">
      <%- Target.find_each do |t| %>
        <div class="progress">
          <div class="progress-bar" role="progressbar" aria-valuenow="<%= targets[t.id] %>" aria-valuemin="0" aria-valuemax="<%= max_target %>" style="min-width: <%=targets[t.id]%>%;">
            <strong ><%= t.name %> <%= targets[t.id] %> грн. </strong> 
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title><%= @title || "Stockroom" %></title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= favicon_link_tag 'apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png' %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body style="padding-top: 70px;">
  <div id="wrap">
    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <div class="container-fluid">

      <div class="row hidden-print">
        <div class="col-sm-6 col-sm-offset-3 text-center">
          <%= render 'layouts/messages' %>
        </div>
      </div>
<!-- Button trigger modal -->
      <div class="row">
        <div class="col-xs-3 hidden-print ">
          <%= yield :sidebar %>
        </div>

        <div class="col-xs-9 container" >
          <%= yield %>
        </div>
      </div>

    </div>
  </div>

  <%= render 'layouts/footer' %>

</body>
</html>

app/views/layouts/application.html.erb.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Stockroom" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Stockroom</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>